server:
  port: 8080
  address: localhost
  tomcat:
    ajp:
      protocol: AJP/1.3
      port: 9091

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/toy?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC

  jpa:
    open-in-view: false #웹요청이 완료될때까지 영속성을 가짐 (성능상 안 좋음)
    show-sql: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false # auto increment 에 대한 설정
    properties:
      hibernate:
        connection:
          CharSet: utf-8
          CharacterEncoding: utf-8
          useUnicode: true
        format_sql: true



#      naming: #엔티티와 테이블에 대한 네이밍 전략 옵션이 추가되면 camel 형식대로 컬럼명
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    hibernate:
#      # create 는 어플리케이션을 실행할때 데이터베이스를 생성한다.
#      ddl-auto: create
#
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    generate-ddl: true
#    # 관련된 동작과 매핑된 sql을 콘솔에 출력 여부
#    show-sql: true

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
