logging:
  level: debug


server:
  port: 8080
  address: localhost

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/toy?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC

  jpa:

    open-in-view: false
    hibernate:
      ddl-auto: create
      naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true


#    hibernate:
#      # create 는 어플리케이션을 실행할때 데이터베이스를 생성한다.
#      ddl-auto: create
#
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    generate-ddl: true
#    # 관련된 동작과 매핑된 sql을 보여줄꺼냐 or 안보여줄꺼냐
#    show-sql: true